@startuml contexto

hide circle
hide methods
hide empty members

skinparam usecase {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}

skinparam actor {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}

actor Indivíduo
actor :Profissional de Saúde: as PS
actor :Software Cliente: as CLIENTE 
actor Administrador
actor :Responsável Técnico: as TECNICO

(Medicamentos\nsistema) as SISTEMA

Indivíduo --> SISTEMA
PS --> SISTEMA
CLIENTE --> SISTEMA

Administrador -up-> SISTEMA
TECNICO -up-> SISTEMA

@enduml