@startuml dados

hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}

entity "Grupo Terapêutico" as GT {
    <<PK>> ATC
    nome
}

entity Medicamento {
    denominação genérica
    forma farmacêutica
    concentração
}

entity "Forma farmacêutica" as FF <<lookup table>> {
    código
    descrição
}

entity Componente <<enum>> {
    ESPECIALIZADO
    HOSPITALAR
    ESTRATÉGICO
    BÁSICO
} 

GT |o-- GT : pai
Medicamento }o.right.|| GT : classificado em
Medicamento }o..|| FF : " descrição"
Medicamento }o.left.|| Componente

@enduml